spring.application.name=pokedex

spring.datasource.url=jdbc:h2:file:./data/pokedex;AUTO_SERVER=true
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# Affichage temporaire des requêtes pour observer les jointures et le problème N+1.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Signification :
# jdbc:h2:mem:pokedex : crée une base temporaire appelée pokedex.
# sa : nom d’utilisateur H2 par défaut.
# mot de passe vide.
# console.enabled=true : active l’interface web H2.
# create-drop : crée les tables au démarrage et les supprime à l’arrêt.
